### ISSUE TITLE
 Use goimport instead of go fmt

### ISSUE THREAD

**Issue by xlr-8** [cycloidio/cycloid-hooks#9]
After discussing with Ivan and working on autospotting, it seems like the usage of 'go imports' rather than 'go fmt' is more widely spread. We are currently using 'go fmt' in both our hooks and Makefile. It could be good to update those in order to switch.

For those wondering the differences, they are not *that* big:
http://goinbigdata.com/goimports-vs-gofmt/

**Comment by ifraixedes** [comment]
Not big, but I think that's cool to avoid silly conflicts with the import packages order
